# Generated by Django 5.0.6 on 2025-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_customerinvoiceitem_customerinvoicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoiceitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
