# Generated by Django 5.0.6 on 2025-03-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_customerinvoiceitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinvoice',
            options={'permissions': (('view_my_invoices', 'Can view assigned invoices'),)},
        ),
    ]
