# Generated by Django 5.0.6 on 2025-03-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_customerinvoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid')], default='unpaid', max_length=50),
        ),
    ]
