# Generated by Django 5.0.6 on 2025-03-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_customerinvoice_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinvoice',
            options={'permissions': (('view_my_invoices', 'Can view assigned invoices'), ('generate_customerinvoice', 'Can generate customer invoice'))},
        ),
    ]
