# Generated by Django 5.0.6 on 2025-03-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_customerinvoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.customerinvoice'),
        ),
        migrations.AlterField(
            model_name='customerinvoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.customerinvoice'),
        ),
    ]
