# Generated by Django 5.0.6 on 2024-08-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('change_profile', 'Can change profile'),), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
