# Generated by Django 5.0.6 on 2024-07-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttype',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipmenttype',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
