# Generated by Django 5.0.6 on 2024-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_shipmenttype_name_en_shipmenttype_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydestination',
            name='city_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverydestination',
            name='city_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverydestination',
            name='country_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverydestination',
            name='country_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
