# Generated by Django 5.0.6 on 2024-07-30 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_deliverydestination_city_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='logistic.deliveryhistory'),
        ),
    ]
