# Generated by Django 5.0.6 on 2024-07-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_historicallogisticconfig_logisticconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticconfig',
            name='initial_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='logistic.deliverystatus'),
        ),
    ]
