# Generated by Django 5.0.6 on 2024-07-30 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_alter_logisticconfig_initial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhistory',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='logistic.vehicle'),
        ),
    ]
