# Generated by Django 5.0.6 on 2024-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_vehicledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledocument',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
