# Generated by Django 5.0.6 on 2024-08-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0013_alter_shipment_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentvehicle',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='logistic.shipment'),
        ),
    ]
