# Generated by Django 5.0.6 on 2024-08-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0015_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhistory',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='logistic.vehicle'),
        ),
    ]
