# Generated by Django 5.0.6 on 2024-08-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0016_alter_deliveryhistory_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentvehicle',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='logistic.shipment'),
        ),
    ]
