# Generated by Django 5.0.6 on 2024-08-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0018_shipmentdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-pk'], 'permissions': (('view_all_customer_vehicles', 'Can view all customer vehicles'),)},
        ),
    ]
