# Generated by Django 5.0.6 on 2025-03-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0021_pricingtype_pricing_vehicletasktype_vehicletask'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatus',
            name='status_type',
            field=models.CharField(blank=True, choices=[('initial', 'initial'), ('complete', 'complete')], max_length=50, null=True),
        ),
    ]
