# Generated by Django 5.0.6 on 2025-03-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0022_deliverystatus_status_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletask',
            options={'permissions': (('view_my_tasks', 'Can view assigned tasks'),)},
        ),
    ]
