# Generated by Django 5.0.6 on 2025-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0023_alter_vehicletask_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletasktype',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicletasktype',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
