# Generated by Django 5.0.6 on 2025-03-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0025_alter_vehicle_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': (('generate_invoice', 'Can generate invoice'),)},
        ),
    ]
