# Generated by Django 5.0.6 on 2025-03-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0026_alter_invoice_options'),
        ('main', '0003_onetimelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydestination',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.file'),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.deliverystatus'),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='logistic.vehicle'),
        ),
        migrations.AlterField(
            model_name='deliverystatus',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.file'),
        ),
        migrations.AlterField(
            model_name='invoicevehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.vehicle'),
        ),
        migrations.AlterField(
            model_name='logisticconfig',
            name='initial_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistic.deliverystatus'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.pricingtype'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.shipmentcompany'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.shipmenttype'),
        ),
        migrations.AlterField(
            model_name='shipmentcompany',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.file'),
        ),
        migrations.AlterField(
            model_name='shipmentdocument',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file'),
        ),
        migrations.AlterField(
            model_name='shipmenttype',
            name='complete_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete_status', to='logistic.deliverystatus'),
        ),
        migrations.AlterField(
            model_name='shipmenttype',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.file'),
        ),
        migrations.AlterField(
            model_name='shipmenttype',
            name='initial_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.deliverystatus'),
        ),
        migrations.AlterField(
            model_name='shipmentvehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.deliverydestination'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file'),
        ),
        migrations.AlterField(
            model_name='vehiclephoto',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.vehiclephotocategory'),
        ),
        migrations.AlterField(
            model_name='vehiclephoto',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file'),
        ),
        migrations.AlterField(
            model_name='vehicletask',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.vehicletasktype'),
        ),
        migrations.AlterField(
            model_name='vehicletasktype',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.file'),
        ),
    ]
