# Generated by Django 5.0.6 on 2025-03-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0027_alter_deliverydestination_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='status_type',
            field=models.CharField(blank=True, choices=[('on_the_way', 'ON THE WAY'), ('on_hand', 'ON HAND'), ('shipped', 'SHIPPED'), ('manifest', 'MANIFEST')], max_length=50, null=True),
        ),
    ]
