# Generated by Django 5.0.6 on 2025-03-18 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0028_alter_deliverystatus_status_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='container_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_hybrid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliverystatus',
            name='status_type',
            field=models.CharField(blank=True, choices=[('on_hand', 'ON HAND'), ('manifest', 'MANIFEST'), ('on_the_way', 'ON THE WAY'), ('shipped', 'SHIPPED'), ('picked_up', 'PICKED UP'), ('arrived', 'ARRIVED'), ('handed_over', 'HANDED OVER')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='VehicleTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_title', models.BooleanField(default=False)),
                ('title_type', models.CharField(blank=True, choices=[('no_title', 'NO TITLE'), ('exportable', 'EXPORTABLE'), ('pending', 'PENDING'), ('bos', 'BOS'), ('lien', 'LIEN'), ('mv907', 'MV907'), ('rejected', 'REJECTED')], max_length=50, null=True)),
                ('title_received_date', models.DateField(blank=True, null=True)),
                ('title_no', models.CharField(blank=True, max_length=100, null=True)),
                ('title_state', models.CharField(blank=True, max_length=100, null=True)),
                ('title_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='logistic.vehicle')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
