# Generated by Django 5.0.6 on 2025-03-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0029_vehicle_container_no_vehicle_is_hybrid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletitle',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='logistic.vehicle'),
        ),
    ]
